## works

```
$ salt-call --local cmd.run cmd='uname -a'
[INFO    ] Executing command '/sbin/zfs -?' in directory '/root'
[INFO    ] Executing command '/sbin/zfs -?' in directory '/root'
[INFO    ] Executing command 'uname -a' in directory '/root'
local:
    FreeBSD salt.freebsd.org 10.1-RELEASE FreeBSD 10.1-RELEASE #0 r274401: Tue Nov 11 21:02:49 UTC 2014     root@releng1.nyi.freebsd.org:/usr/obj/usr/src/sys/GENERIC  amd64
```
## broken

```
$ salt-call --local cmd.run cmd='uname -a' use_vt=True
[INFO    ] Executing command '/sbin/zfs -?' in directory '/root'
[INFO    ] Executing command '/sbin/zfs -?' in directory '/root'
[INFO    ] Executing command 'uname -a' in directory '/root'
[WARNING ] Failed to spawn the VT: [Errno 6] Device not configured: '/dev/tty'
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
UnboundLocalError: local variable 'proc' referenced before assignment
Traceback (most recent call last):
  File "/root/venv-salt/bin/salt-call", line 10, in <module>
    execfile(__file__)
  File "/root/salt/scripts/salt-call", line 11, in <module>
    salt_call()
  File "/root/salt/salt/scripts.py", line 220, in salt_call
    client.run()
  File "/root/salt/salt/cli/call.py", line 69, in run
    caller.run()
  File "/root/salt/salt/cli/caller.py", line 234, in run
    ret = self.call()
  File "/root/salt/salt/cli/caller.py", line 138, in call
    ret['return'] = func(*args, **kwargs)
  File "/root/salt/salt/modules/cmdmod.py", line 630, in run
    use_vt=use_vt)
  File "/root/salt/salt/modules/cmdmod.py", line 463, in _run
    proc.close(terminate=True, kill=True)
UnboundLocalError: local variable 'proc' referenced before assignment
Traceback (most recent call last):
  File "/root/venv-salt/bin/salt-call", line 10, in <module>
    execfile(__file__)
  File "/root/salt/scripts/salt-call", line 11, in <module>
    salt_call()
  File "/root/salt/salt/scripts.py", line 220, in salt_call
    client.run()
  File "/root/salt/salt/cli/call.py", line 69, in run
    caller.run()
  File "/root/salt/salt/cli/caller.py", line 234, in run
    ret = self.call()
  File "/root/salt/salt/cli/caller.py", line 138, in call
    ret['return'] = func(*args, **kwargs)
  File "/root/salt/salt/modules/cmdmod.py", line 630, in run
    use_vt=use_vt)
  File "/root/salt/salt/modules/cmdmod.py", line 463, in _run
    proc.close(terminate=True, kill=True)
UnboundLocalError: local variable 'proc' referenced before assignment
[ERROR   ] Command 'uname -a' failed with return code: 1
[ERROR   ] output:
```
