### Description of Issue/Question

When configuring salt with ssl keys for the kubernetes module, it doesn't work. cc: @mcalmer who originally wrote support. The code in question [is here](https://github.com/saltstack/salt/blame/818100b8e7e8f9c3c524f7f3355a2f9e83f63361/salt/modules/kubernetes.py#L171-L172). I'll have a PR shortly with test to fix this.

### Setup
I setup a [test kubernetes cluster using minikube](https://kubernetes.io/docs/getting-started-guides/minikube/) and configured `/etc/salt/minion` with the bare defaults but changed `master` to localhost and added:

```yaml
kubernetes.api_url: 'https://192.168.99.100:8443'
kubernetes.certificate-authority-file: '/home/jeff/.minikube/ca.crt'
kubernetes.client-certificate-file: '/home/jeff/.minikube/client.crt'
kubernetes.client-key-file: '/home/jeff/.minikube/client.key'
```

### Steps to Reproduce Issue
```
(ve) [root@omniscience salt]# salt-call kubernetes.nodes
[WARNING ] /home/jeff/git/salt/salt/utils/__init__.py:794: DeprecationWarning: Use of 'salt.utils.fopen' detected. This function has been moved to 'salt.utils.files.fopen' as of Salt Oxygen. This warning will be removed in Salt Neon.

2017-10-21 19:35:22,944 WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(336265225, u'[SSL] PEM lib (_ssl.c:2718)'),)': /api/v1/nodes
2017-10-21 19:35:22,944 WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(336265225, u'[SSL] PEM lib (_ssl.c:2718)'),)': /api/v1/nodes
[WARNING ] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(336265225, u'[SSL] PEM lib (_ssl.c:2718)'),)': /api/v1/nodes
2017-10-21 19:35:22,945 WARNING Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(336265225, u'[SSL] PEM lib (_ssl.c:2718)'),)': /api/v1/nodes
2017-10-21 19:35:22,945 WARNING Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(336265225, u'[SSL] PEM lib (_ssl.c:2718)'),)': /api/v1/nodes
[WARNING ] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(336265225, u'[SSL] PEM lib (_ssl.c:2718)'),)': /api/v1/nodes
2017-10-21 19:35:22,946 WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(336265225, u'[SSL] PEM lib (_ssl.c:2718)'),)': /api/v1/nodes
2017-10-21 19:35:22,946 WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(336265225, u'[SSL] PEM lib (_ssl.c:2718)'),)': /api/v1/nodes
[WARNING ] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(336265225, u'[SSL] PEM lib (_ssl.c:2718)'),)': /api/v1/nodes
[ERROR   ] Exception when calling CoreV1Api->list_node: HTTPSConnectionPool(host='192.168.99.100', port=8443): Max retries exceeded with url: /api/v1/nodes (Caused by SSLError(SSLError(336265225, u'[SSL] PEM lib (_ssl.c:2718)'),))
Traceback (most recent call last):
  File "/home/jeff/git/salt/salt/modules/kubernetes.py", line 216, in nodes
    api_response = api_instance.list_node()
  File "/home/jeff/git/salt/ve/lib/python2.7/site-packages/kubernetes/client/apis/core_v1_api.py", line 13990, in list_node
    (data) = self.list_node_with_http_info(**kwargs)
  File "/home/jeff/git/salt/ve/lib/python2.7/site-packages/kubernetes/client/apis/core_v1_api.py", line 14086, in list_node_with_http_info
    collection_formats=collection_formats)
  File "/home/jeff/git/salt/ve/lib/python2.7/site-packages/kubernetes/client/api_client.py", line 335, in call_api
    _preload_content, _request_timeout)
  File "/home/jeff/git/salt/ve/lib/python2.7/site-packages/kubernetes/client/api_client.py", line 148, in __call_api
    _request_timeout=_request_timeout)
  File "/home/jeff/git/salt/ve/lib/python2.7/site-packages/kubernetes/client/api_client.py", line 371, in request
    headers=headers)
  File "/home/jeff/git/salt/ve/lib/python2.7/site-packages/kubernetes/client/rest.py", line 250, in GET
    query_params=query_params)
  File "/home/jeff/git/salt/ve/lib/python2.7/site-packages/kubernetes/client/rest.py", line 223, in request
    headers=headers)
  File "/home/jeff/git/salt/ve/lib/python2.7/site-packages/urllib3/request.py", line 66, in request
    **urlopen_kw)
  File "/home/jeff/git/salt/ve/lib/python2.7/site-packages/urllib3/request.py", line 87, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "/home/jeff/git/salt/ve/lib/python2.7/site-packages/urllib3/poolmanager.py", line 321, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/home/jeff/git/salt/ve/lib/python2.7/site-packages/urllib3/connectionpool.py", line 668, in urlopen
    **response_kw)
  File "/home/jeff/git/salt/ve/lib/python2.7/site-packages/urllib3/connectionpool.py", line 668, in urlopen
    **response_kw)
  File "/home/jeff/git/salt/ve/lib/python2.7/site-packages/urllib3/connectionpool.py", line 668, in urlopen
    **response_kw)
  File "/home/jeff/git/salt/ve/lib/python2.7/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/jeff/git/salt/ve/lib/python2.7/site-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
MaxRetryError: HTTPSConnectionPool(host='192.168.99.100', port=8443): Max retries exceeded with url: /api/v1/nodes (Caused by SSLError(SSLError(336265225, u'[SSL] PEM lib (_ssl.c:2718)'),))
Error running 'kubernetes.nodes': HTTPSConnectionPool(host='192.168.99.100', port=8443): Max retries exceeded with url: /api/v1/nodes (Caused by SSLError(SSLError(336265225, u'[SSL] PEM lib (_ssl.c:2718)'),))
```

### Versions Report
I wanted to do some development on the kubernetes module to fix some bugs. I pulled the latest develop at 818100b8e7e8f9c3c524f7f3355a2f9e83f63361.

```bash
(ve) [root@omniscience salt]# salt-minion --versions-report
Salt Version:
           Salt: 2017.7.0-747-g818100b
 
Dependency Versions:
           cffi: 1.11.2
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: 2.5.1
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Sep  5 2017, 08:53:59)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.2
            ZMQ: 4.1.6
 
System Versions:
           dist: fedora 26 Twenty Six
         locale: UTF-8
        machine: x86_64
        release: 4.12.13-300.fc26.x86_64
         system: Linux
        version: Fedora 26 Twenty Six
```