When trying to spin up a VM on Joyent using salt-cloud, the following stacktrace occurs:

```
[DEBUG   ] Joyent Response Status Code: 200
[ERROR   ] There was a profile error: dictionary changed size during iteration
Traceback (most recent call last):
  File "/root/SaltStack/salt/salt/cloud/cli.py", line 255, in run
    self.config.get('names')
  File "/root/SaltStack/salt/salt/cloud/__init__.py", line 1378, in run_profile
    ret[name] = self.create(vm_)
  File "/root/SaltStack/salt/salt/cloud/__init__.py", line 1248, in create
    output = self.clouds[func](vm_)
  File "/root/SaltStack/salt/salt/cloud/clouds/joyent.py", line 307, in create
    query_instance(vm_)
  File "/root/SaltStack/salt/salt/cloud/clouds/joyent.py", line 227, in query_instance
    'wait_for_ip_interval_multiplier', vm_, __opts__, default=1),
  File "/root/SaltStack/salt/salt/utils/cloud.py", line 2012, in wait_for_ip
    data = update_callback(*update_args, **update_kwargs)
  File "/root/SaltStack/salt/salt/cloud/clouds/joyent.py", line 198, in _query_ip_address
    data = show_instance(vm_['name'], call='action')
  File "/root/SaltStack/salt/salt/cloud/clouds/joyent.py", line 633, in show_instance
    node = get_node(name)
  File "/root/SaltStack/salt/salt/cloud/clouds/joyent.py", line 614, in get_node
    nodes = list_nodes()
  File "/root/SaltStack/salt/salt/cloud/clouds/joyent.py", line 724, in list_nodes
    ret[node['name']] = reformat_node(item=node, full=full)
  File "/root/SaltStack/salt/salt/cloud/clouds/joyent.py", line 690, in reformat_node
    for key in six.iterkeys(item):  # iterate over a copy of the keys
RuntimeError: dictionary changed size during iteration
```

The instance does get created on the Joyent account, but since the `salt-cloud -p` command stacktraces, the VM never gets bootstrapped with salt.

Note: salt-cloud works just fine with the joyent driver on the 2015.2 branch.

ping @techhat 
