I'm suddenly receiving this error message on my Salt Master (2015.5.2) when trying to run any commands against any of my minions (minions are also 2015.5.2 and a combination of Ubuntu or Windows 2008 R2). See below:

> salt:~# salt 'servername' state.show_highstate
> [CRITICAL] Could not deserialize msgpack message: Unexpected Error in MworkerThis often happens > when trying to read a file not in binary mode.Please open an issue and include the following error:
> unpack(b) recieved extra data.

I'm not sure if it's related, but I'm also receiving the following error when running **salt-run manage.versions**

> salt:~# salt-run manage.versions
> [CRITICAL] Could not deserialize msgpack message: Unexpected Error in MworkerThis often
> happens when trying to read a file not in binary mode.Please open an issue and include the
> following error: unpack(b) recieved extra data.
> unpack(b) recieved extra data.
> [ERROR   ] An un-handled exception was caught by salt's global exception handler:
> IOError: [Errno 2] No such file or directory: '/var/cache/salt/master/jobs/c4
> /677de1330880597ff52d40bc532392/jid'
> Traceback (most recent call last):
> File "/usr/bin/salt-run", line 10, in <module>
>    salt_run()
>  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 250, in salt_run
>    client.run()
>  File "/usr/lib/python2.7/dist-packages/salt/cli/run.py", line 54, in run
>    runner.run()
>  File "/usr/lib/python2.7/dist-packages/salt/runner.py", line 166, in run
>    False)  # Don't daemonize
>  File "/usr/lib/python2.7/dist-packages/salt/client/mixins.py", line 381, in _proc_function
>    return self.low(fun, low)
>  File "/usr/lib/python2.7/dist-packages/salt/client/mixins.py", line 336, in low
>    mminion=self.mminion,
>  File "/usr/lib/python2.7/dist-packages/salt/utils/job.py", line 51, in store_job
>    mminion.returners[jidstore_fstr](False, passed_jid=load['jid'])
>  File "/usr/lib/python2.7/dist-packages/salt/returners/local_cache.py", line 124, in prep_jid
>    with salt.utils.fopen(os.path.join(jid_dir_, 'jid'), 'wb+') as fn_:
>  File "/usr/lib/python2.7/dist-packages/salt/utils/**init**.py", line 1045, in fopen
>    fhandle = open(_args, *_kwargs)
> IOError: [Errno 2] No such file or directory: '/var/cache/salt/master/jobs/c4
> /677de1330880597ff52d40bc532392/jid'
> Traceback (most recent call last):
>  File "/usr/bin/salt-run", line 10, in <module>
>    salt_run()
> File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 250, in salt_run
>    client.run()
>  File "/usr/lib/python2.7/dist-packages/salt/cli/run.py", line 54, in run
>    runner.run()
>  File "/usr/lib/python2.7/dist-packages/salt/runner.py", line 166, in run
>    False)  # Don't daemonize
>  File "/usr/lib/python2.7/dist-packages/salt/client/mixins.py", line 381, in _proc_function
>    return self.low(fun, low)
>  File "/usr/lib/python2.7/dist-packages/salt/client/mixins.py", line 336, in low
>    mminion=self.mminion,
>  File "/usr/lib/python2.7/dist-packages/salt/utils/job.py", line 51, in store_job
>    mminion.returners[jidstore_fstr](False, passed_jid=load['jid'])
>  File "/usr/lib/python2.7/dist-packages/salt/returners/local_cache.py", line 124, in prep_jid
>    with salt.utils.fopen(os.path.join(jid_dir_, 'jid'), 'wb+') as fn_:
>  File "/usr/lib/python2.7/dist-packages/salt/utils/**init**.py", line 1045, in fopen
>    fhandle = open(_args, *_kwargs)
> IOError: [Errno 2] No such file or directory: '/var/cache/salt/master/jobs/c4
> /677de1330880597ff52d40bc532392/jid'
