After calling state.highstate I get this traceback:

```
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/pymodules/python2.7/salt/scripts.py", line 76, in salt_call
    client.run()
  File "/usr/lib/pymodules/python2.7/salt/cli/__init__.py", line 265, in run
    caller.run()
  File "/usr/lib/pymodules/python2.7/salt/cli/caller.py", line 131, in run
    ret = self.call()
  File "/usr/lib/pymodules/python2.7/salt/cli/caller.py", line 72, in call
    ret['return'] = func(*args, **kwargs)
  File "/usr/lib/pymodules/python2.7/salt/modules/state.py", line 201, in highstate
    cache_name=kwargs.get('cache_name', 'highstate')
  File "/usr/lib/pymodules/python2.7/salt/state.py", line 2179, in call_highstate
    self.load_dynamic(matches)
  File "/usr/lib/pymodules/python2.7/salt/state.py", line 1857, in load_dynamic
    if syncd['grains']:
TypeError: list indices must be integers, not str
```

I suspect the call to 

```
self.state.functions['saltutil.sync_all'](list(matches))
```

in salt/state.py although if I run sync_all no error occurs

salt-minion versions-report:

```
           Salt: 0.16.0-166-gef35fe1
         Python: 2.7.3 (default, Apr 10 2013, 05:13:16)
         Jinja2: 2.6
       M2Crypto: 0.21.1
 msgpack-python: 0.1.10
   msgpack-pure: Not Installed
       pycrypto: 2.6
         PyYAML: 3.10
          PyZMQ: 13.0.0
            ZMQ: 3.2.2

```

salt-master versions-report:

```
     Salt: 0.16.0-166-gef35fe1
         Python: 2.7.3 (default, Aug  1 2012, 05:14:39)
         Jinja2: 2.6
       M2Crypto: 0.21.1
 msgpack-python: 0.1.10
   msgpack-pure: Not Installed
       pycrypto: 2.4.1
         PyYAML: 3.10
          PyZMQ: 13.0.0
            ZMQ: 3.2.2


```
