It appears that the newly introduced `progressbar` option chokes if used on a higher-level master.

```
[root@server ~]# salt -p \* test.ping                                                                                                                                                                                             
[ERROR   ] An un-handled exception was caught by salt's global exception handler:###########################################################################################################| Elapsed Time: 0:00:00 Returns: [31/31]
ValueError: Value out of range
Traceback (most recent call last):
  File "/usr/bin/salt", line 10, in <module>
    salt_main()
  File "/usr/lib/python2.6/site-packages/salt/scripts.py", line 349, in salt_main
    client.run()
  File "/usr/lib/python2.6/site-packages/salt/cli/salt.py", line 179, in run
    self._progress_ret(progress, out)
  File "/usr/lib/python2.6/site-packages/salt/cli/salt.py", line 272, in _progress_ret
    salt.output.update_progress(self.config, progress, self.progress_bar, out)
  File "/usr/lib/python2.6/site-packages/salt/output/__init__.py", line 77, in update_progress
    progress_outputter(progress, progress_iter)
  File "/usr/lib/python2.6/site-packages/salt/output/progress.py", line 21, in output
    bar.update(ret['return_count'])
  File "/usr/lib/python2.6/site-packages/progressbar/__init__.py", line 272, in update
    raise ValueError('Value out of range')
ValueError: Value out of range
Traceback (most recent call last):
  File "/usr/bin/salt", line 10, in <module>
    salt_main()
  File "/usr/lib/python2.6/site-packages/salt/scripts.py", line 349, in salt_main
    client.run()
  File "/usr/lib/python2.6/site-packages/salt/cli/salt.py", line 179, in run
    self._progress_ret(progress, out)
  File "/usr/lib/python2.6/site-packages/salt/cli/salt.py", line 272, in _progress_ret
    salt.output.update_progress(self.config, progress, self.progress_bar, out)
  File "/usr/lib/python2.6/site-packages/salt/output/__init__.py", line 77, in update_progress
    progress_outputter(progress, progress_iter)
  File "/usr/lib/python2.6/site-packages/salt/output/progress.py", line 21, in output
    bar.update(ret['return_count'])
  File "/usr/lib/python2.6/site-packages/progressbar/__init__.py", line 272, in update
    raise ValueError('Value out of range')
ValueError: Value out of range
```
