Suddenly all my attempts at starting or stopping ec2 nodes fail with the bellow error.... 

```
salt-cloud --versions-report             
            Salt: 2014.7.0-1934-g91b9632
          Python: 2.7.5 (default, Nov  3 2014, 14:26:24)
          Jinja2: 2.7.3
        M2Crypto: 0.21.1
  msgpack-python: 0.4.2
    msgpack-pure: Not Installed
        pycrypto: 2.6.1
         libnacl: Not Installed
          PyYAML: 3.10
           ioflo: Not Installed
           PyZMQ: 14.3.1
            RAET: Not Installed
             ZMQ: 4.0.4
            Mako: 1.0.0
 Apache Libcloud: 0.16.0
```

```
sudo salt-cloud --map=/etc/salt/cloud.map --parallel -ldebug
...
[DEBUG   ] Generating minion keys for 'spark-worker-10'
[DEBUG   ] Generating minion keys for 'spark-worker-9'
[DEBUG   ] Generating minion keys for 'spark-worker-8'
[DEBUG   ] MasterEvent PUB socket URI: ipc:///var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: ipc:///var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Sending event - data = {'profile': 'spark_master', 'event': 'starting create', '_stamp': '2014-12-13T23:12:26.546275', 'name': 'spark-master', 'provider': 'aws-gu-spark:ec2'}
[ERROR   ] There was a query error: unpack(b) received extra data.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/cloud/cli.py", line 316, in run
    ret = mapper.run_map(dmap)
  File "/usr/lib/python2.7/site-packages/salt/cloud/__init__.py", line 1992, in run_map
    out = self.create(master_profile, local_master=local_master)
  File "/usr/lib/python2.7/site-packages/salt/cloud/__init__.py", line 1240, in create
    output = self.clouds[func](vm_)
  File "/usr/lib/python2.7/site-packages/salt/cloud/clouds/ec2.py", line 2040, in create
    vm_['name'], vm_['profile'], 'ec2', vm_['provider']
  File "/usr/lib/python2.7/site-packages/salt/utils/cloud.py", line 2015, in cachedir_index_add
    index = msgpack.load(fh_)
  File "_unpacker.pyx", line 140, in msgpack._unpacker.unpack (msgpack/_unpacker.cpp:140)
  File "_unpacker.pyx", line 123, in msgpack._unpacker.unpackb (msgpack/_unpacker.cpp:123)
ExtraData: unpack(b) received extra data.
```
