Getting the following exception when running cp.get_url:

```
The minion function caused an exception: Traceback (most recent call last):
      File "c:\salt\bin\lib\site-packages\salt\minion.py", line 1142, in _thread_return
        return_data = func(*args, **kwargs)
      File "c:\salt\bin\lib\site-packages\salt\modules\cp.py", line 278, in get_url
        return __context__['cp.fileclient'].get_url(path, dest, False, saltenv)
      File "c:\salt\bin\lib\site-packages\salt\fileclient.py", line 598, in get_url
        response = query['handle']
    KeyError: 'handle'
```

The exact command being run starts with:

```
salt 'Win*' cp.get_url https://
```

```
root@master:~# salt --versions-report
           Salt: 2015.5.1
         Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.3.0
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.0.1
           RAET: Not Installed
            ZMQ: 4.0.4
           Mako: Not Installed
```
