We get errors when trying to apply `user.present` to our OpenBSD 5.9 minion running the OS-included `salt-2015.8.5` binary package. We currently apply the state from our Ubuntu 14.04 master running the upstream `2015.8.8+ds-2` version of the `salt-master` package.

Among others, we use this simple state that works for all our Linux flavours and FreeBSD:

```
dev-account:
  user.present:
    - name: dev
    - fullname: Developer Account
    - shell: /usr/local/bin/bash
    - home: /home/dev/
    - password: $6$HkBrNSD9$ikWom3HZeuF8HZDBvd6vWf.g8twf57EB5BYxaFuXC/APA.lEHL9ciVYyD5duISyfyQXhqpJkn2aPNToFxWC3c/
```

We get the following error from the OpenBSD minion:

```
          ID: dev-account
    Function: user.present
        Name: dev
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/local/lib/python2.7/site-packages/salt/state.py", line 1624, in call
                  **cdata['kwargs'])
                File "/usr/local/lib/python2.7/site-packages/salt/loader.py", line 1491, in wrapper
                  return f(*args, **kwargs)
                File "/usr/local/lib/python2.7/site-packages/salt/states/user.py", line 457, in present
                  lcpre = __salt__['user.get_loginclass'](name)
                File "/usr/local/lib/python2.7/site-packages/salt/modules/useradd.py", line 509, in get_loginclass
                  ret = line.split(None, 1)[1]
              IndexError: list index out of range
     Started: 19:09:14.276952
    Duration: 50.02 ms
     Changes:
```

Corresponding debug logs:

```
2016-04-12 19:09:14,277 [salt.utils.lazy                                            ][DEBUG   ][21596] LazyLoaded user.present
2016-04-12 19:09:14,277 [salt.state                                                 ][INFO    ][21596] Running state [dev] at time 19:09:14.276952
2016-04-12 19:09:14,277 [salt.state                                                 ][INFO    ][21596] Executing state user.present for dev
2016-04-12 19:09:14,280 [salt.utils.lazy                                            ][DEBUG   ][21596] LazyLoaded shadow.info
2016-04-12 19:09:14,281 [salt.utils.lazy                                            ][DEBUG   ][21596] LazyLoaded cmd.has_exec
2016-04-12 19:09:14,282 [salt.loaded.int.module.cmdmod                              ][INFO    ][21596] Executing command 'grep "^dev:" /etc/master.passwd| cut -f6,7 -d:' in directory '/root'
2016-04-12 19:09:14,292 [salt.loaded.int.module.cmdmod                              ][DEBUG   ][21596] stdout: 0:0
2016-04-12 19:09:14,295 [salt.utils.lazy                                            ][DEBUG   ][21596] LazyLoaded user.info
2016-04-12 19:09:14,306 [salt.utils.lazy                                            ][DEBUG   ][21596] LazyLoaded file.gid_to_group
2016-04-12 19:09:14,307 [salt.loaded.int.module.cmdmod                              ][INFO    ][21596] Executing command 'grep "^dev:" /etc/master.passwd| cut -f6,7 -d:' in directory '/root'
2016-04-12 19:09:14,316 [salt.loaded.int.module.cmdmod                              ][DEBUG   ][21596] stdout: 0:0
2016-04-12 19:09:14,317 [salt.loaded.int.module.cmdmod                              ][INFO    ][21596] Executing command ['userinfo', 'dev'] in directory '/root'
2016-04-12 19:09:14,324 [salt.loaded.int.module.cmdmod                              ][DEBUG   ][21596] stdout: login    dev
passwd  *************
uid 1002
groups  dev
change  NEVER
class   
gecos   Developer Account,,,
dir /home/dev/
shell   /usr/local/bin/bash
expire  NEVER
2016-04-12 19:09:14,327 [salt.state                                                 ][ERROR   ][21596] An exception occurred in this state: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/salt/state.py", line 1624, in call
    **cdata['kwargs'])
  File "/usr/local/lib/python2.7/site-packages/salt/loader.py", line 1491, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/salt/states/user.py", line 457, in present
    lcpre = __salt__['user.get_loginclass'](name)
  File "/usr/local/lib/python2.7/site-packages/salt/modules/useradd.py", line 509, in get_loginclass
    ret = line.split(None, 1)[1]
IndexError: list index out of range

2016-04-12 19:09:14,327 [salt.state                                                 ][INFO    ][21596] Completed state [dev] at time 19:09:14.326972
```
