```
travis@precise64:/home/travis$ sudo salt-call --local --retcode-passthrough state.sls          
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
TypeError: sls() takes at least 1 argument (0 given)
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/pymodules/python2.7/salt/scripts.py", line 77, in salt_call
    client.run()
  File "/usr/lib/pymodules/python2.7/salt/cli/__init__.py", line 303, in run
    caller.run()
  File "/usr/lib/pymodules/python2.7/salt/cli/caller.py", line 135, in run
    ret = self.call()
  File "/usr/lib/pymodules/python2.7/salt/cli/caller.py", line 78, in call
    ret['return'] = func(*args, **kwargs)
TypeError: sls() takes at least 1 argument (0 given)
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/pymodules/python2.7/salt/scripts.py", line 77, in salt_call
    client.run()
  File "/usr/lib/pymodules/python2.7/salt/cli/__init__.py", line 303, in run
    caller.run()
  File "/usr/lib/pymodules/python2.7/salt/cli/caller.py", line 135, in run
    ret = self.call()
  File "/usr/lib/pymodules/python2.7/salt/cli/caller.py", line 78, in call
    ret['return'] = func(*args, **kwargs)
TypeError: sls() takes at least 1 argument (0 given)
```
